spring:
  datasource:
    url: jdbc:postgresql://192.168.1.216:5432/testdatabase
    username: postgresuser
    password: securepassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1888MB
      max-request-size: 1000MB

  async:
    request-timeout: 3688888

server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
